name 'jlyheden-tinyproxy'
version '0.0.1'
author 'Johan Lyheden <johan@lyheden.com>'
license 'Apache 2.0 license'
project_page '://github.com/jlyheden/puppet-tinyproxy.git'
source 'git@github.com:jlyheden/puppet-tinyproxy.git'
summary 'Puppet module to manage tinyproxy'
description 'Puppet module to manage tinyproxy'
dependency 'puppetlabs/concat', '>=1.0.0'
